### ISSUE TITLE
Ehancement

### ISSUE THREAD

**Issue by stwins60** [mariehposa/sca-project#1]
Salam, I was going through your projects and you have interesting projects. Can you try integrating this project with Kubernetes?

**Comment by mariehposa** [comment]
Hello @stwins60! Thanks for the suggestion, but this project is mainly for this [article](https://dev.to/mariehposa/how-to-deploy-an-application-to-aws-ec2-instance-using-terraform-and-ansible-3e78).

**Comment by stwins60** [comment]
Got it.
